export { PhantasmaAPI } from './core/rpc/phantasma.js';
export type {
  ABIContract,
  ABIEvent,
  ABIMethod,
  ABIParameter,
  Account,
  AccountTransactions,
  Archive,
  Auction,
  Balance,
  Block,
  BuildInfoResult,
  Chain,
  Channel,
  CursorPaginatedResult,
  Dapp,
  Event as RpcEvent,
  EventExtended,
  EventExtendedTyped,
  ExtendedEventData,
  Governance,
  Interop,
  KeyValue,
  Leaderboard,
  LeaderboardRow,
  Nexus as RpcNexus,
  NFT,
  Oracle,
  Organization,
  Paginated,
  Peer,
  PhantasmaVmConfig,
  Platform,
  Receipt,
  Script,
  SendRawTx,
  SignatureResult,
  Stake,
  Storage,
  Swap,
  Token,
  TokenData,
  TokenExternal,
  TokenPrice,
  TokenSchemasResult,
  TokenSeries,
  TokenSeriesResult,
  TransactionData,
  Validator,
  VmNamedVariableSchemaResult,
  VmStructSchemaResult,
  VmVariableSchemaResult,
} from './core/rpc/interfaces/index.js';
export {
  vmStructSchemaFromRpcResult,
  vmVariableSchemaFromRpcResult,
} from './core/rpc/helpers/index.js';

export {
  ContractTxHelper,
  buildContractArtifactBundle,
  buildContractArtifactManifest,
  coerceContractBytes,
  normalizeContractName,
  ExecutionState,
  Transaction,
} from './core/tx/index.js';
export type {
  BuildContractArtifactBundleParams,
  BuildContractArtifactManifestParams,
  ContractArtifactBundle,
  ContractArtifactFileEntry,
  ContractArtifactManifest,
  ContractBinaryInput,
  ContractScriptBuildParams,
  ContractTransactionBuildParams,
  ContractTransactionSignParams,
} from './core/tx/index.js';

export {
  Contracts,
  Decoder,
  EventKind,
  Opcode,
  ScriptBuilder,
  TypeAuction,
  VMObject,
  VMType,
  decodeVMObject,
  getChainValueEventData,
  getGasEventData,
  getInfusionEventData,
  getMarketEventData,
  getString,
  getTokenEventData,
  getTransactionSettleEventData,
} from './core/vm/index.js';

export {
  AccountTrigger,
  Address,
  AddressKind,
  Base16,
  CarbonBinaryReader,
  CarbonBinaryWriter,
  ConsensusMode,
  ContractEvent,
  ContractInterface,
  ContractMethod,
  ContractParameter,
  CustomSerializer,
  Describer,
  DomainSettings,
  Ed25519Signature,
  Entropy,
  OrganizationTrigger,
  PBinaryReader,
  PBinaryWriter,
  PhantasmaKeys,
  PollChoice,
  PollPresence,
  PollState,
  PollValue,
  PollVote,
  Serialization,
  Stack,
  StakeReward,
  Timestamp,
  TokenTrigger,
  TriggerResult,
  bigIntToTwosComplementLE,
  readBlob,
  twosComplementLEToBigInt,
  writeBlob,
} from './core/types/index.js';
export type { CustomReader, CustomWriter } from './core/types/index.js';

export {
  Bytes16,
  Bytes32,
  Bytes64,
  CarbonBlob,
  CarbonTokenFlags,
  CreateTokenSeriesTxHelper,
  CreateTokenTxHelper,
  FieldType,
  IntX,
  MetadataField,
  MintNonFungibleTxHelper,
  MintPhantasmaNonFungibleTxHelper,
  ModuleId,
  NftRomBuilder,
  PhantasmaNftRomBuilder,
  PhantasmaNftMintInfo,
  PhantasmaNftMintResult,
  SeriesInfo,
  SeriesInfoBuilder,
  SignedTxMsg,
  SmallString,
  StandardMeta,
  TokenContract_Methods,
  TokenHelper,
  TokenInfo,
  TokenInfoBuilder,
  TokenMetadataBuilder,
  TokenSchemas,
  TokenSchemasBuilder,
  TokenSchemasJson,
  TokenSeriesMetadataBuilder,
  TxMsg,
  TxMsgBurnFungible,
  TxMsgBurnFungibleGasPayer,
  TxMsgBurnNonFungible,
  TxMsgBurnNonFungibleGasPayer,
  TxMsgCall,
  TxMsgCallMulti,
  TxMsgMintFungible,
  TxMsgMintNonFungible,
  TxMsgPhantasma,
  TxMsgPhantasmaRaw,
  TxMsgSigner,
  TxMsgSpecialResolution,
  TxMsgTrade,
  TxMsgTransferFungible,
  TxMsgTransferFungibleGasPayer,
  TxMsgTransferNonFungibleMulti,
  TxMsgTransferNonFungibleMultiGasPayer,
  TxMsgTransferNonFungibleSingle,
  TxMsgTransferNonFungibleSingleGasPayer,
  TxTypes,
  TokenListing,
  VmDynamicStruct,
  VmDynamicVariable,
  VmNamedDynamicVariable,
  VmNamedVariableSchema,
  VmStructArray,
  VmStructFlags,
  VmStructSchema,
  VmType,
  VmVariableSchema,
  Witness,
  findMetadataField,
  nftDefaultMetadataFields,
  parseTokenSchemasJson,
  pushMetadataField,
  seriesDefaultMetadataFields,
  standardMetadataFields,
} from './core/types/Carbon/index.js';
export type { MetadataValueInput } from './core/types/Carbon/index.js';

export {
  ANONYMOUS_NAME,
  ENTRY_CONTEXT_NAME,
  GENESIS_NAME,
  NULL_NAME,
  arrayNumberToUint8Array,
  bigIntToByteArray,
  bytesToHex,
  decodeBase16,
  encodeBase16,
  getDifficulty,
  hexStringToUint8Array,
  hexToBytes,
  isReservedIdentifier,
  isValidIdentifier,
  isValidTicker,
  numberToByteArray,
  reverseHex,
  setLogger,
  stringToUint8Array,
  uint8ArrayToBytes,
  uint8ArrayToNumberArray,
  uint8ArrayToString,
  uint8ArrayToStringDefault,
} from './core/utils/index.js';
export type { Logger } from './core/utils/index.js';

export {
  generateNewSeed,
  generateNewSeedWords,
  generateNewWif,
  getAddressFromWif,
  getPrivateKeyFromWif,
  getPublicKeyFromPrivateKey,
  getWifFromPrivateKey,
  signData,
  verifyData,
} from './core/tx/utils.js';

export { EasyConnect } from './core/link/easyConnect.js';
export { EasyScript, Nexus } from './core/link/easyScript.js';
export { PhantasmaLink } from './core/link/phantasmaLink.js';
export { ProofOfWork } from './core/link/interfaces/ProofOfWork.js';
export type { LinkAccount, LinkFile } from './core/link/index.js';
export type { PrebuiltTransactionSignResult } from './core/link/phantasmaLink.js';

export {
  Signature,
  SignatureKind,
  NativeContractKind,
  TokenFlags,
  TokenSeriesMode,
  getAddressFromLedger,
  getAddressFromPrivateKey,
  getAddressFromPublicKey,
  getAddressPublicKeyFromPublicKey,
} from './core/index.js';
export type {
  CarbonBlobLike,
  ContractDescriptor,
  FeeOptionsLike,
  KeyPair,
  Ledger,
  StackLike,
  TokenDescriptor,
} from './core/index.js';
